version: "3"

services:
  meli-proxy-api:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    expose:
      - 6379